apiVersion: v1
kind: Service
metadata:
  name: dns-test-service
  namespace: networking-demo
  labels:
    app: dns-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: cni-demo
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: networking-demo
  labels:
    app: dns-demo
spec:
  type: ExternalName
  externalName: httpbin.org
  ports:
  - port: 80
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-test-pod
  namespace: networking-demo
  labels:
    app: dns-demo
spec:
  containers:
  - name: dns-test
    image: busybox:1.35
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "=== DNS Resolution Tests ==="
        
        echo "1. Resolving ClusterIP service:"
        nslookup clusterip-demo
        nslookup clusterip-demo.networking-demo.svc.cluster.local
        
        echo "2. Resolving ExternalName service:"
        nslookup external-service
        nslookup external-service.networking-demo.svc.cluster.local
        
        echo "3. Resolving Kubernetes DNS:"
        nslookup kubernetes.default.svc.cluster.local
        
        echo "4. Testing service connectivity:"
        wget -qO- --timeout=5 http://clusterip-demo/ | head -3 || echo "Service access failed"
        
        echo "5. Testing external service:"
        wget -qO- --timeout=5 http://external-service/ | head -3 || echo "External service access failed"
        
        echo "=== Waiting 60 seconds ==="
        sleep 60
      done 